name: template

version: 1.0.1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^17.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  flutter_platform_widgets: ^9.0.0
  flutter_native_splash: ^2.4.7
  in_app_review: ^2.0.11
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_lint: ^0.3.5

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/app/icon/
    - assets/images/app/splash/

  fonts:
    - family: NotoSans
      fonts: 
        - asset: assets/fonts/NotoSans-Regular.ttf
