name: template

version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: 9.0.0
  flutter_native_splash: 2.4.6
  firebase_analytics: 11.5.0
  firebase_core: 3.14.0
  firebase_performance: 0.10.1
  firebase_storage: 12.4.7
  intl: 0.20.2 # flutter gen-l10n
  shared_preferences: 2.5.3
  rate_my_app: 2.3.1
  provider: 6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: 1.2.0
  flutter_lints: 6.0.0 

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/app/icon/
    - assets/images/app/splash/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf